config/routes.rb
Wegrow::Application.routes.draw do
  resources :leads

  root :to => 'leads#new'
  get 'home' => "pages#home"
  get 'how' => "pages#howitworks"

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  attr_accessible :email, :name, :email_1, :association_1, :email_2, :association_2, :email_3, :association_3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

before_filter :disable_nav, only: [:new, :show]  #hiding nav on certain pages re: http://stackoverflow.com/questions/13395153/how-to-render-partial-on-everything-except-a-certain-action

def disable_nav
  @disable_nav = true
end

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def howitworks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
<img src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/wegrow.png" class="footer-icon" style="margin: 0 auto">
<br>
WeGrow Inc.
</div>

app/views/layouts/_header.html.erb
header

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WeGrow</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<!-- start google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<!-- end google fonts -->

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="js/modernizr.js"></script>
	<script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>
	<%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
	<link rel="shortcut icon" href="https://s3.amazonaws.com/checkmybackdoor/images/How+To/wegrow.png">
</head>
<body>
	<div class="container-fluid">
		<%= render 'layouts/header' unless @disable_nav %>

		<%= yield %>
		<div style="padding-bottom:100px"></div>

		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/leads/_form.html.erb
<h4 style="font-family: lato; margin: -10px 0px 0px 0px">Get started by entering your email. You can also enter the people you want to get feedback from on your team or in your organization.</h4>  
<br>
<%= simple_form_for(@lead, html: { class: "form-horizontal"}) do |f| %>
<table>
  <tr>
    <%= f.text_area :email, placeholder: "Your work email", class: "lead-form", :autocomplete => :off, :rows => 1 %>
  </tr>
  <tr>
    <%= f.text_area :name, placeholder: "Your name", class: "lead-form", :autocomplete => :off, :rows => 1 %>
  </tr>
  <div class="divider">Your team (optional)</div>
  <tr>
    <%= f.text_area :email_1, placeholder: "Manager's Email", class: "lead-form", :autocomplete => :off, :rows => 1 %>
  </tr>
  <tr>
    <%= f.text_area :email_2, placeholder: "Peer #1 Email", class: "lead-form", :autocomplete => :off, :rows => 1 %>
  </tr>
  <tr>
    <%= f.text_area :email_3, placeholder: "Peer #2 Email", class: "lead-form", :autocomplete => :off, :rows => 1 %>
  </tr>
</table>
<%= f.submit "Get started", class: "home-button", id: "lead-submit" %>

<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Listing leads</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads.each do |lead| %>
  <tr>
    <td><%= link_to 'Show', lead %></td>
    <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
    <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
    <!-- Header -->
    <div class="intro-header">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-12">
    				<div class="intro-message">
    					<h1>Get better at your job with more frequent feedback</h1>
    					<!-- <h3>without breaking others</h3> -->
    					<hr class="intro-divider">
    					<ul class="list-inline intro-social-buttons">
    						<li>

                            <!-- old buttons from original template
                            <a href="/auth/twitter" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">start writing anonymously</span></a> -->
                            <button type="button" href="#leads" data-toggle="modal" class="home-button" id="button-1" style="width:300px">
                            	Get started
                            </button>
                            <br>
                            OR
                            <br>
                            <button type="button" href="#leads" data-toggle="modal" class="home-button" id="button-2" style="width:300px">
                            	Take a peek around
                            </button>
                        </li>
                        <li>
<!--                                 <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->




    <!-- Modal -->
    <div class="modal fade" id="leads">
    	<div class="modal-dialog">
    		<div class="modal-content" style="border-radius: 0px">
    			<div class="modal-header">
    				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    				<h2 style="text-align: center; font-family: lato">Start giving & receiving feedback</h2>
    			</div>
    			<div class="modal-body">

    				<!-- start form body -->
    				<div class="leads-modal">

				  					

    					<%= render 'form' %>

    					




    				</div>
    				<!-- end form body -->

    			</div><!-- /.modal-content -->
    		</div><!-- /.modal-dialog -->
    	</div><!-- /.modal -->
    </div>









    <!-- Page Content -->

    <div class="content-section-a">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-5 col-sm-6">
    				<hr class="section-heading-spacer">
    				<div class="clearfix"></div>
    				<h2 class="section-heading">What is WeGrow?</h2>
    				<p class="lead">WeGrow is the simplest feedback gathering tool on the planet for individuals, teams, and companies. We make it stupid simple to give and get feedback directly or anonymously so you or your team can diagnose strengths to lean on and opportunity areas to improve.</p>
    			</div>
    			<div class="col-lg-5 col-lg-offset-2 col-sm-6">
    				<img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/dashboard.png" alt="" style="margin: 50px 0px 0px 0px">
    			</div>
    		</div>

    	</div>
    	<!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
    				<hr class="section-heading-spacer">
    				<div class="clearfix"></div>
    				<h2 class="section-heading">How does it work?</h2>
    				<p class="lead">We ask the people that matter in your teams and organization quick and easy questions about your performance so you can improve. You also answer the same questions about yourself and your coworkers through whatever channel works best for you: email, web, or our mobile apps (coming soon).</p>
    			</div>
    			<div class="col-lg-5 col-sm-pull-6  col-sm-6">
    				<img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/reply.png" alt="" style='margin-left:0px;margin-top:50px'>
    			</div>
    		</div>

    	</div>
    	<!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-5 col-sm-6">
    				<hr class="section-heading-spacer">
    				<div class="clearfix"></div>
    				<h2 class="section-heading">What's the catch?</h2>
    				<p class="lead">No catch. Just honest feedback from the people that matter. You tell us what you want to improve, and we get you started.</p>
    			</div>
    			<div class="col-lg-5 col-lg-offset-2 col-sm-6">
    				<img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/select.png" alt="" style='margin-left:0px'>
    			</div>
    		</div>

    	</div>
    	<!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-6">
    				<h2>Get started</h2>
    			</div>
    			<div class="col-lg-6">
    				<ul class="list-inline banner-social-buttons">
<!--                         <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li> -->
                        <li>
                            <!-- original button
                            <a href="/auth/twitter" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Sign up with Twitter</span></a> -->
                           <button type="button" href="#leads" data-toggle="modal" class="home-button" id="button-1" style="width:300px">
                            	Get started
                            </button>
                        </li>
<!--                         <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li> -->
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

app/views/leads/show.html.erb
    <!-- Header -->
    <div class="intro-header">

    	<div class="container">

    		<div class="row">
    			<div class="col-lg-12">
    				<div class="intro-message">
    					<h1 style="margin-top: -50px">Thanks! We'll occassionally ask your teammates for feedback and send you a digest every week!</h1>

    				</div>
    			</div>
    		</div>

    	</div>
    	<!-- /.container -->

    </div>
    <!-- /.intro-header -->

app/views/pages/home.html.erb
    <!-- Header -->
    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Get better at your job with more frequent feedback</h1>
                        <!-- <h3>without breaking others</h3> -->
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                
                            <!-- old buttons from original template
                                <a href="/auth/twitter" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">start writing anonymously</span></a> -->
                                <button type="button" onclick=window.location='/auth/twitter' class="home-button" id="button-1" style="width:300px">
                                Get started
                              </button>
                              <br>
                              OR
                                <br>
                                <button type="button" onclick=window.location='/' class="home-button" id="button-2" style="width: 300px">
                                Take a peek around
                              </button>
                          </li>
                          <li>
<!--                                 <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                            </li> -->
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">What is WeGrow?</h2>
                    <p class="lead">WeGrow is the simplest feedback gathering tool on the planet for individuals, teams, and companies. We make it stupid simple to give and get feedback directly or anonymously so you or your team can diagnose strengths to lean on and opportunity areas to improve.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/dashboard.png" alt="" style="margin: 50px 0px 0px 0px">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">How does it work?</h2>
                    <p class="lead">We ask the people that matter in your teams and organization quick and easy questions about your performance so you can improve. You also answer the same questions about yourself and your coworkers through whatever channel works best for you: email, web, or our mobile apps (coming soon).</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/reply.png" alt="" style='margin-left:0px;margin-top:50px'>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">What's the catch?</h2>
                    <p class="lead">No catch. Just honest feedback from the people that matter. You tell us what you want to improve, and we get you started.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="https://s3.amazonaws.com/checkmybackdoor/images/How+To/select.png" alt="" style='margin-left:0px'>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Get started</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
<!--                         <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li> -->
                        <li>
                            <!-- original button
                            <a href="/auth/twitter" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Sign up with Twitter</span></a> -->
                            <button type="button" onclick=window.location='/auth/twitter' class="home-button" id="button-1" style="width:300px;">
                                Sign up
                              </button>
                        </li>
<!--                         <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li> -->
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

app/views/pages/howitworks.html.erb
howitworks

app/views/pages/test.html.erb
<%=